### ISSUE TITLE
Checkpoint

### ISSUE THREAD

**Issue by ghost** [qrpike/instagram-approve-pending-followers#2]
CheckpointError: Instagram call checkpoint for this action!

How do I fix this?

**Comment by shuhulkaul** [comment]
.catch(( err ) => {
        
        console.log('err1:', err.message);
        if(err.url)
        {   
       
           checkpoint(req, res, err.url);
        }
        else{
           
            error(err.message);
            console.log("url is null");
        }
     
    }
    );
